### ISSUE TITLE
Build on macOS

### ISSUE THREAD

**Issue by jo-m** [VLOGroup/imageutilities#8]
Hey all

I could not find any mention of supported operating systems anywhere in the project. I assume you only tested on Linux (which distributions/versions?).

I am trying to compile this project on macOS, from the latest commit 6faaa0854.

```
# remove all occurencies of '-fopenmp' in imageutilities/cmake/compiler_settings.cmake.txt
$EDITOR cmake/compiler_settings.cmake.txt
cd build
make
```

This however fails with the log attached. Any ideas?
[log.txt](https://github.com/VLOGroup/imageutilities/files/1087567/log.txt)

**Comment by gottfriedm** [comment]
Hi,

it should work on Linux and Windows, as far as I know we didn't do any testing on Mac, sorry.

To get it working, using gcc instead of clang and in general making the environment as similar to Linux as possible should make things easier. You can also try to disable the ndarray module for now, this one uses quite some new C++11/14 features and might give trouble.

Good luck!
